services:
  vulnerabilityapi:
    build:
      context: ./VulnerabilityApi
      dockerfile: Dockerfile
    container_name: vulnerability-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/vulnerabilities
    depends_on:
      - redis
      - postgres
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  redis:
    image: redislabs/redisearch:latest
    container_name: redis
    ports:
      - "6379:6379"
    command:
      ["redis-server", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vulnerabilities
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  redis-data:
  postgres-data:
  pgadmin-data:
